### ISSUE TITLE
[Bug]: Laravel 11

### ISSUE THREAD

**Issue by zoltes** [parfaitementweb/filament-country-field#3]
### What happened?

Freshly installed Laravel 11, latest Filamentphp, trying to install Filament-country-code, composer has been updated and I get this:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires parfaitementweb/filament-country-field * -> satisfiable by parfaitementweb/filament-country-field[1.0.0, 2.0.0].
    - parfaitementweb/filament-country-field[1.0.0, 2.0.0] require illuminate/contracts ^10.0 -> found illuminate/contracts[v10.0.0, ..., v10.48.2] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require parfaitementweb/filament-country-field:*" to figure out if any version is installable, or "composer require parfaitementweb/filament-country-field:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

### How to reproduce the bug

Laravel 11, Filamentphp 3
> composer update
> composer require parfaitementweb/filament-country-field

### Package Version

2

### PHP Version

8.2.4

### Laravel Version

11

### Which operating systems does with happen with?

macOS

**Comment by AlexisSerneels** [comment]
Fixed in https://github.com/parfaitementweb/filament-country-field/releases/tag/2.0.1
